# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "<MC_BASE_PATH>/install/offline-builder/centos7/rpms", "/home/vagrant/rpms"
  config.vm.synced_folder "<MC_BASE_PATH>/install/offline-builder/centos7/docker-images", "/home/vagrant/docker-images"
  config.vm.synced_folder "<MC_BASE_PATH>/src/host-node/resources/k8s_templates", "/home/vagrant/k8s_templates"
  config.vbguest.auto_update = false
  config.vm.define "worker.<WS_ID>" do |worker|
    worker.vm.box = "mycloud-worker"
    worker.vm.hostname = "worker.<WS_ID>"
    worker.vm.network "public_network", bridge: "<IF_NAME>"<STATIC_IP>
    worker.vm.provider "virtualbox" do |v|
      v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
      v.name = "worker.<WS_ID>"
      v.memory = 2048
      v.cpus = 2
    end
    worker.vm.provision "shell", path: "../../../bootstrap_scripts/k8s/bootstrap_worker.sh"
  end
end