# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # Kubernetes Worker Node
  config.vm.define "worker.<WS_ID>" do |worker|
    worker.vm.box = "mycloud-worker"
    worker.vm.hostname = "worker.<WS_ID>"
    worker.vm.network "public_network", bridge: "<IF_NAME>"<STATIC_IP>
    worker.vm.provider "virtualbox" do |v|
      v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
      v.name = "worker.<WS_ID>"
      v.memory = 2048
      v.cpus = 2
    end
    worker.vm.provision "shell", path: "../../../bootstrap_scripts/k8s/bootstrap_worker.sh"
  end
end