# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # Kubernetes Master Server
  config.vm.define "master.<WS_ID>" do |master|
    master.vm.box = "mycloud-master"
    master.vm.hostname = "master.<WS_ID>"
    master.vm.network "public_network", bridge: "<IF_NAME>"<STATIC_IP>
    master.vm.provider "virtualbox" do |v|
      v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
      v.name = "master.<WS_ID>"
      v.memory = 4096
      v.cpus = 4
    end
    master.vm.provision "file", source: "../../../deployment_templates", destination: "$HOME/deployment_templates"
    master.vm.provision "shell", path: "../../../bootstrap_scripts/k8s/bootstrap_master.sh", args: "'<REGISTRY_IP>'"
  end
end