# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provision "shell", path: "./bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "worker.base" do |worker|
    worker.vm.box = "centos/7"
    worker.vm.hostname = "worker.base"
    worker.vm.provider "virtualbox" do |v|
      v.name = "worker.base"
      v.memory = 2048
      v.cpus = 2
    end
  end
end