# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "./rpms", "/var/tmp/rpms"
  config.vm.define "mycloud.base" do |mycloud|
    mycloud.vm.box = "centos/7"
    mycloud.vm.hostname = "mycloud.base"
    mycloud.vm.network "public_network"
    mycloud.vm.provider "virtualbox" do |v|
      v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
      v.name = "mycloud-offline.builder"
      v.memory = 2048
      v.cpus = 1
    end
    
    mycloud.vm.provision "shell", path: "./fetch.sh"
  end
end