# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provision "shell", path: "./bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "master.base" do |master|
    master.vm.box = "centos/7"
    master.vm.hostname = "master.base"
    master.vm.provider "virtualbox" do |v|
      v.name = "master.base"
      v.memory = 4096
      v.cpus = 4     
    end
  end
end
